### ISSUE TITLE
Fix Mongoose model document reference types

### ISSUE THREAD

**Issue by sdiv877** [se701team3/Forgettable#106]
## Description
 
Currently references to other documents are stored in the type `[Schema.Types.ObjectId]` within models.  Trying to create documents with multiple values within these reference fields/with a non empty field would cause errors.  
The [solution](https://stackoverflow.com/a/51407995) to the problem seems to be to change the type to  `mongoose.Types.ObjectId[]`.

## Acceptance Criteria

- [x] Change the `User`, `Person` and `Encounter` models to use `mongoose.Types.ObjectId[]` for object references

**Comment by butterplup** [comment]
LGTM 👍
