### ISSUE TITLE
Create small version of person card

### ISSUE THREAD

**Issue by lin8231** [se701team3/Forgettable#110]
## Description
 
Person card comes in two different sizes: normal (done in #60), and small (this)
![image](https://user-images.githubusercontent.com/62003343/157814058-c2094c86-d5da-4c52-a81b-d5a268e06517.png)

## Acceptance Criteria

- [ ] Card is correct size
- [ ] Has correct styling
- [ ] Displays person's profile picture
- [ ] Displays person's name
- [ ] Displays first met information, formatted correctly. 

## Implementation details

n/a

## Testing notes

n/a

**Comment by lin8231** [comment]
@rainasong Please review and approve ticket.

**Comment by rainasong** [comment]
The ticket LGTM!
