### ISSUE TITLE
Add extra fields to Person model

### ISSUE THREAD

**Issue by sdiv877** [se701team3/Forgettable#114]
## Description
 
A few extra fields are needed for the Person model, for the Frontend
## Acceptance Criteria

- [ ] Replace `first_name` and `last_name` with `full_name` in the `person.model.ts` file
- [ ] Change name of `time_added` to `time_updated`
- [ ] Add `gender`, `location`, `social-media`, `first_met` and `image` fields

**Comment by butterplup** [comment]
LGTM 👍
