### ISSUE TITLE
PUT /api/encounter/:id

### ISSUE THREAD

**Issue by hajineats** [se701team3/Forgettable#116]
## Description
Create an endpoint for changing a encounter's data in the database

## Acceptance Criteria
- [x] Create a new function in `encounter.service.ts` called `updateEncounter()` (or equivalent)
- [x] Create a new function in `encounter.controller.ts` called `updateEncounter()` (or equivalent)
- [x] Attach the `updateEncounter()` function to `/encounters/:id` in `encounter.route.ts`

## Implementation details

- [ ] Request requires a `firebase_token` in headers
- [x] Success gives 204 No content
- [x] Invalid request (eg encounter id that is invalid) body returns 400 Bad Request
- [x] If encounter cannot be found 404 Not Found
- [ ] Invalid token returns 401 Unauthorized

## Testing notes

* Tests that encounter can be successfully modified if encoutner object with that object id exists
* Tests that encounter will not be modified but throw error (400) if encounter id is not well-formed
* Tests that encounter will not be modified but throw error (404) if encounter object does not exist

**Comment by lin8231** [comment]
Issue LGTM.
