### ISSUE TITLE
Implement Firebase Authentication function for use by endpoints

### ISSUE THREAD

**Issue by jimwang6012** [se701team3/Forgettable#121]
## Description
Implement a function to authenticate users and associate them with their own unique auth_id in MongoDB

## Acceptance Criteria

- [x] Implement working Firebase Authentication
- [x] Create a function called `firebaseAuth()` in `middleware.ts`, used to authenticate requesting users (Refactoring)
- [x] Integrate Firebase Authentication into all endpoints

**Comment by sdiv877** [comment]
LGTM!

**Comment by AdamAWiener** [comment]
**NOTE:** Ticket has been changed to implement the function as middleware for all endpoints.
