### ISSUE TITLE
Add `title` field to `encounter` model

### ISSUE THREAD

**Issue by AdamAWiener** [se701team3/Forgettable#130]
## Description
 
An extra field: `title` needs to be added to the `encounter` model.

## Acceptance Criteria

- [ ] `title` field added to encounter model
- [ ] Relevant changes (if any) made to `encounter.service` and `encounter.controller`

## Implementation details

The new `title` field should be a string and should be a required field.

## Testing notes

na

**Comment by jimwang6012** [comment]
Issue LGTM

**Comment by rainasong** [comment]
Issue LGTM!
