### ISSUE TITLE
Create Encounter details side panel

### ISSUE THREAD

**Issue by rainasong** [se701team3/Forgettable#139]
## Description
The following UI is shared between multiple pages, so a component is made for it.
![Screen Shot 2022-03-14 at 8 38 54 PM](https://user-images.githubusercontent.com/37087904/158125960-4a1830a9-f3c4-4ccc-86e0-fe41727c8302.png)

## Acceptance Criteria

- [x] Shows the title of the encounter
- [x] Shows Persons involved in the encounter
- [x] Shows the date of the encounter
- [x] Shows details of the encounter
- [x] Handles cases where certain fields don't exist
- [x] Has appropriate placeholders/UI logic if fields don't exist
- [x] The side panel is scrollable, but stick to the top of the page when other parts of the page are scrolling
- [x] Date format is correct

## Implementation details

This should be similar in implementation to #109 

## Testing notes

n/a

**Comment by lin8231** [comment]
Issue approved :)

**Comment by lin8231** [comment]
Issue approved :)
