### ISSUE TITLE
Add query params to GET /encounters

### ISSUE THREAD

**Issue by jimwang6012** [se701team3/Forgettable#143]
## Description
Add query param to the `GET /encounters` endpoint for filtering and pagination

## Acceptance Criteria
- [x] Edit the `getAllEncounters` function in `encounter.service.ts` to accept and process the incoming query param
- [x] If a query param is empty, it is ignored

* Query params to be added
   ~~Title~~
   ~~Date~~
   ~~Location~~
   ~~Description ???~~
   ~~Associated person's name~~
- [x] Use one query param called `term` (works better with Algolia/FE)

## Implementation details
Example usage `http://localhost:5000/api/encounters?term=a string of some kind`

**Comment by sdiv877** [comment]
LGTM!

**Comment by jimwang6012** [comment]
Acceptance criteria are updated in order to work better with Algolia/FE, since only one parameter is needed for the `GET /encounters` endpoint.
