### ISSUE TITLE
Update person drawer to have option to be displayed as static drawer

### ISSUE THREAD

**Issue by lin8231** [se701team3/Forgettable#147]
## Description
* Currently, the PeronDrawer component is made for the purpose of the Dashboard and the People list page
  * In this implementation, it is displayed on the right side, as a collapsible drawer (See below)
  * ![image](https://user-images.githubusercontent.com/62003343/158301283-94a76a97-a7d1-4e68-8e88-4dbbd682f1f6.png)

* We also need a version of this component that exists on the leftside for the "Person" page (see below:
  * ![image](https://user-images.githubusercontent.com/62003343/158301257-de5d23bc-5f8a-4381-9e13-48f7629cc07b.png)

## Acceptance Criteria

- [ ] Drawer conditionally renders on left/right depending on a bool prop
- [ ] Styling changes accordingly and correctly depending on which version it is 
- [ ] Does not break existing styles 
- [ ] Shows "Edit" button if is the static version 

## Implementation details

n/a

## Testing notes

n/a

**Comment by lin8231** [comment]
@butterplup Please approve issue

**Comment by butterplup** [comment]
LGTM ✌️
