### ISSUE TITLE
Create `GET /users` endpoint

### ISSUE THREAD

**Issue by AdamAWiener** [se701team3/Forgettable#150]
## Description
 
Implement the `GET /users` endpoint.

## Acceptance Criteria

- [x]  Create a new function in `user.controller.ts` called `getUser()`
- [x]  Attatch the `getUser()` function to `GET /users` in `user.route.ts`

## Implementation details

The user should be retrieved using the user_id in the auth header.

## Testing notes

Testing may be challenging due to close interaction with the external auth system.

**Comment by jimwang6012** [comment]
LGTM!
