### ISSUE TITLE
Add `time_updated` field to `encounter` model

### ISSUE THREAD

**Issue by AdamAWiener** [se701team3/Forgettable#154]
## Description
 
Add `time_updated` field to `encounter.model` to track when the encounter was last edited.

## Acceptance Criteria

- [ ] `time_updated` field added to model
- [ ] Field defaults to `date.now()`
- [ ] Adjust tests to pass with new field

## Implementation details

na

## Testing notes

na

**Comment by schi314** [comment]
LGTM
