### ISSUE TITLE
Adjust `encounter` test cases to pass with new `title` field

### ISSUE THREAD

**Issue by AdamAWiener** [se701team3/Forgettable#155]
## Description
 
A new change #130 has added a new field to `encounter.model` which has broken test cases.
These test cases need to be adjusted to include and pass with the new title field.

## Acceptance Criteria

- [ ] Test cases account for `title` field and all pass.

## Implementation details

The fix is likely just to do with adding the field to the declared test data.

## Testing notes

![image](https://user-images.githubusercontent.com/63831771/158325975-3baadc9f-3a94-4014-ab43-807229db1b2e.png)

**Comment by Sherman-Chin** [comment]
LGTM

**Comment by schi314** [comment]
LGTM
