### ISSUE TITLE
Change `person` model's `full_name` to `first_name` and `last_name`

### ISSUE THREAD

**Issue by AdamAWiener** [se701team3/Forgettable#157]
## Description
 
Frontend requires the `full_name` field to be split into `first_name` and `last_name`.

## Acceptance Criteria

- [ ] remove `full_name` and add `first_name` and `last_name`.
- [ ] All existing `person` tests pass

## Implementation details

First name should be required and last name should not.
Both should be strings.

**Comment by butterplup** [comment]
LGTM ✅
