### ISSUE TITLE
Replace query params of GET persons/ with a single 'term' param

### ISSUE THREAD

**Issue by sdiv877** [se701team3/Forgettable#161]
## Description
 
In order to work better with Algolia/FE only one parameter is needed for the GET persons/ endpoint.

## Acceptance Criteria

- [x] Replace current query param setup of GET persons/ with one `term` param
- [ ] Add unit tests 

## Implementation details

Example usage `http://localhost:5000/api/persons?term=a string of some kind`

**Comment by lanxdrey19** [comment]
LGTM

**Comment by jimwang6012** [comment]
LGTM!
