### ISSUE TITLE
Refactor test auth token generation to util file

### ISSUE THREAD

**Issue by AdamAWiener** [se701team3/Forgettable#163]
## Description
 
Currently, each of the `route` test files contain their own copy of the auth token generator:
![image](https://user-images.githubusercontent.com/63831771/158339390-7e97899e-ee22-49a4-9dea-8051548922ff.png)

This code can be refactored into a util function for use within all three test files
## Acceptance Criteria

- [ ] Refactor into function `generateTestAuthToken` and place into test util file
- [ ] All test cases pass as before the refactor

## Implementation details

The `beforeAll()` call and `databaseOperations.connectDatabase()` calls must remain for the tests to run properly

## Testing notes

na

**Comment by jimwang6012** [comment]
LGTM!
