### ISSUE TITLE
Add pagination to GET /persons and GET /encounters

### ISSUE THREAD

**Issue by schi314** [se701team3/Forgettable#165]
## Description
 
Allow option to retrieve subset of data in pages

## Acceptance Criteria

- [x] Add optional `limit` and `page` query params to both endpoints
- [x] Correctly returns `limit` number of entries at `page=x`

## Implementation details

Both query params must be present for pagination

**Comment by butterplup** [comment]
LGTM 😎

**Comment by rainasong** [comment]
This is done for GET /persons and GET /encounters now!
