### ISSUE TITLE
Create frontend API call functions 

### ISSUE THREAD

**Issue by lin8231** [se701team3/Forgettable#171]
## Description
API calls are made from many different areas of the app, and many are repeated. We need a set of functions which does all the API call logic, so the pages can just call these functions rather than implementing its own logic. 

## Acceptance Criteria

- [ ] All user APIs are functional 
- [ ] All Person APIs are functional
- [ ] All Encounter APIs are functional 
- [ ] All API calls have error handling logic
- [ ] Functions are tested. 

## Implementation details

n/a

## Testing notes

n/a

**Comment by lusicle** [comment]
lgtm 😎
