### ISSUE TITLE
Sort out frontend auth routing and conditional rendering

### ISSUE THREAD

**Issue by lin8231** [se701team3/Forgettable#173]
## Description
 
Auth routing/conditional rendering needs work on the frontend. Currently, these things happen:

![image](https://user-images.githubusercontent.com/62003343/158402596-459ca340-d718-443c-9b84-d3885435f43e.png)
![image](https://user-images.githubusercontent.com/62003343/158402614-1c7c06b2-8621-4d50-9320-4dc09c5b8b69.png)

## Acceptance Criteria

- [x] User is redirected to sign in page if they visit any other page while not logged in
- [x] User is redirected to dashboard if they try to visit the sign in page while logged in 
- [x] Sign in page and other pages should not show up at the same time as shown in screenshots.
- [x] Auth token needs to be stored in local storage, and it needs to be able to handle when it expires 

## Implementation details

n/a

## Testing notes

Please test routing if possible

**Comment by noahjade** [comment]
Solved with PR #204
