### ISSUE TITLE
Add tests for API calls (frontend)

### ISSUE THREAD

**Issue by rainasong** [se701team3/Forgettable#177]
## Description
 
A suite of tests is needed to ensure API call helpers are correct and functional as expected.

## Acceptance Criteria

- [x] There should be at least one test to cover each function
- [x] The tests should mock API calls
- [x] All tests should pass

## Implementation details

Can use jest library to mock axios and API calls

## Testing notes

n/a

**Comment by noahjade** [comment]
LGTM!
