### ISSUE TITLE
Change `GET /persons` and `GET /encounters` to return empty array when nothing is found

### ISSUE THREAD

**Issue by jimwang6012** [se701team3/Forgettable#181]
## Description
Changing the response of `GET /persons` and `GET /encounters` endpoint to an empty array instead of `204 NO CONTENT` when the user does not have any associated `persons` or `encounters`. This decision was made to allow our endpoints to work better with Frontend. 

## Acceptance Criteria
- [ ] Change the response of the `getAllPeople()` function in `person.controller.ts` from `204 NO CONTENT` to return an empty array in the case that the user has no associated `persons`. 
- [ ] Change the response of the `getAllEncounters()` function in `encounter.controller.ts` from `204 NO CONTENT` to return an empty array in the case that the user has no associated `encounters`.

**Comment by sdiv877** [comment]
LGTM!
