### ISSUE TITLE
Add infinite scroll component

### ISSUE THREAD

**Issue by rainasong** [se701team3/Forgettable#189]
## Description
 
An infinite scroll component is required for multiple pages, so a component is needed.

## Acceptance Criteria

- [ ] Correct prompts displayed at the bottom (when has more items, shows 'Loading'; when does not have anything left, shows 'That's all' or something similar)
- [ ] Should immediately trigger load more action when scrolling to the bottom

## Implementation details

Use package `react-infinite-scroll-component` to speed up development.

## Testing notes

n/a

**Comment by cdra334** [comment]
Looks good!
