### ISSUE TITLE
Add test util for fetching auth_id using a given token.

### ISSUE THREAD

**Issue by AdamAWiener** [se701team3/Forgettable#190]
## Description
 
To create tests for endpoints, User data will have to be made to attribute new encounters and persons to. To create such user data without the use of the POST endpoint, a utility is required to retrieve auth ids.
## Acceptance Criteria

- [ ] Add function `getAuthIdFromToken()` to `test-utils`

## Implementation details

Should take in the token as a string and return the id as a string.
## Testing notes

na

**Comment by sdiv877** [comment]
LGTM 👍  This will make testing much easier!
