### ISSUE TITLE
Fix spacing issues of cards on home page for large screens

### ISSUE THREAD

**Issue by noahjade** [se701team3/Forgettable#206]
## Description
Currently the spacing for the people and encounter summary cards gets messed up on very large screens.

## Acceptance Criteria

- [x] The cards top layer still line up with the bounds of the page (ie, last one is in line with the button)
- [x] The bottom cards do not end up spread out.

## Implementation details
- This is happening because the cards are currently being displayed as flex box space around
- This may require some fiddling with the gap, or even the other component spacing.

## Testing notes
- Make sure to test it still lines up nicely for a range of sizes, including small screens.

**Comment by rainasong** [comment]
I've fixed it in the final bug fixes prs!
