### ISSUE TITLE
Fix SearchBar autocomplete results displaying under avatars

### ISSUE THREAD

**Issue by noahjade** [se701team3/Forgettable#207]
## Description
On the front page, the searchbar autocomplete results currently display underneath the avatar for the person summary cards. We don't want that.

![image](https://user-images.githubusercontent.com/28725774/158772918-3067b8e4-f950-4d62-8b08-285cb2a4b127.png)

## Acceptance Criteria

- [x] Search results appear on top of everything else.

## Implementation details
- This may be an issue with the serachbar component or the avatar styling.
- Alternatively, this could be a revamp of the search bar feature. On the Create Encounter page a MUI Autocomplete component is used to allow the user to search from a predefined list. This is the same behaviour as the search bar, but the formatting of the drop down is already done by MUI. As such, swapping the search bar out with the styled autocomplete component could be cleaner in the long run.

**Comment by rainasong** [comment]
Fixed this in the frontend bugs fixes pr!
