### ISSUE TITLE
Embed encounters with user details to `GET /persons/:id` endpoint

### ISSUE THREAD

**Issue by AdamAWiener** [se701team3/Forgettable#208]
## Description
 
Alter the return of GET /persons/:id to include nested encounter data with person data included.
## Acceptance Criteria

- [ ] body contains required data
- [ ] all existing tests pass
- [ ] add new test to check inclusion of data

## Implementation details

na
## Testing notes

na

**Comment by jimwang6012** [comment]
LGTM!
