### ISSUE TITLE
User Account Login

### ISSUE THREAD

**Issue by ckar364** [se701team3/Forgettable#22]
## Description
Allow the user to login to their account using their email and password as credentials. User credentials would be checked for authenticity. This will ensure only the authorised user is accessing their account, improving security.

## Acceptance Criteria
- [ ] User can enter their email and password credentials easily.
- [ ] Credentials checked for authenticity when submitted.
- [ ] Only authorised users are able to access their account.

## Implementation details
To be decided after initial project skeleton set-up. Note that a "Forgot Password?" feature may be developed in future (Issue #23).

## Testing notes
n/a

## Reviewers
@cdra334

**Comment by noahjade** [comment]
We are now using google accounts for authentication, and other issues cover by other authentication, so I'm going to close this one.
