### ISSUE TITLE
Birthday reminders for Persons on your list

### ISSUE THREAD

**Issue by sher812** [se701team3/Forgettable#229]
## Description
 
A feature to remind users of upcoming birthdays in their people list. 
## Acceptance Criteria

- [ ] Create frontend component to show upcoming birthdays
- [ ] Create endpoints to retrieve upcoming birthdays in User's person list
- [ ] Implement component to existing UI
## Implementation details

A new endpoint will need to be created to retrieve upcoming birthdays in order. Could be a good idea to also set a date limit on upcoming birthdays retrieved e.g. upcoming birthdays in the next 3 months etc...

**Comment by nzbasic** [comment]
**Design Proposal**

**UI:**
![image](https://user-images.githubusercontent.com/54062686/160052229-9b371435-be60-46d1-b524-617544968be5.png)

**Frontend Requirements:**
* Create a new component UpcomingBirthdaySummary
  * Should accept data similar to PersonCardSummary and EncounterCardSummary
  * Clicking on it should take you to their profile 
  * If a birthday is in the current week, it should just say the day of the week (e.g. if today is Tuesday and their birthday is on Friday, it should just say Friday)
  * If a birthday is further away, show the day and month 
* Add the new section to the home page
  * Should have the api call here with the others’
  * Use the same hover effect as the “recently updated” cards
  
**Backend Requirements:**
* Add the route GET /birthdays
  * Return all of the person objects whos birthdays are within 3 months of todays date 
  * Follow the current service/controller pattern

**Comment by aaronyaosong** [comment]
Finished PR on front end components
