### ISSUE TITLE
User Password Reset

### ISSUE THREAD

**Issue by ckar364** [se701team3/Forgettable#23]
## Description
Allow the user to reset their account password if they forgot. Having an automated way for users to reset passwords reduces pressure on customer service resources and increases customer satisfaction through a quick response.

## Acceptance Criteria
- [ ] Allow users to reset their password if they forgot at login.
- [ ] Verify user is the authorised user resetting their password.
- [ ] Prompt user to create a new password.

## Implementation details
To be decided after initial project skeleton set-up. Note this links to issue #22.

## Testing notes
n/a

## Reviewers
@cdra334

**Comment by noahjade** [comment]
We have chosen to use google accounts to simplify authentication, so google handles any password resetting. I'm going to close this issue as it is no longer relevant.
