### ISSUE TITLE
Sign in page needs to be responsive

### ISSUE THREAD

**Issue by lin8231** [se701team3/Forgettable#232]
## Description
Sign in page is currently not responsive, and looks off on larger/smaller screens. e.g.
![image](https://user-images.githubusercontent.com/62003343/158936540-906bdbe2-1f81-447b-8724-629694a99b88.png)

 

## Acceptance Criteria

- [x] Sign in page looks good on all screen sizes

## Implementation details

n/a

## Testing notes

n/a

**Comment by noahjade** [comment]
Thanks for making this issue!! LGTM
