### ISSUE TITLE
Person card needs click handler 

### ISSUE THREAD

**Issue by lin8231** [se701team3/Forgettable#239]
## Description
 
When PersonCard was made, it didn't have a click handler. On the persons page, when a PersonCard is clicked, it must navigate to that person's profile. Hence, a click handler needs to be added

## Acceptance Criteria

- [ ] PersonCard receives click 
- [ ] PersonCard navigates to the right person

## Implementation details

n/a

## Testing notes

n/a

**Comment by butterplup** [comment]
LGTM
