### ISSUE TITLE
Factor "UnknownDetail" into its own component 

### ISSUE THREAD

**Issue by lin8231** [se701team3/Forgettable#240]
## Description
A "unknown detail" element - which is just a simple styled <span>, is being used in multiple places. Although it's a small amount of code to duplicate, it's still duplicated. It would be good to factor this out into its own component, so it can be easily used from anywhere.

## Acceptance Criteria

- [ ] UnkownDetail component looks correct 
- [ ] Existing components which use the <span> unknown detail are updated to use the component instead

## Implementation details

n/a

## Testing notes

n/a

**Comment by hajineats** [comment]
LGTM!
