### ISSUE TITLE
Fix global CSS affecting encounter card bug

### ISSUE THREAD

**Issue by lin8231** [se701team3/Forgettable#243]
## Description
 
Encounter card avatars need fixing due to global CSS:
![image](https://user-images.githubusercontent.com/62003343/158960887-53190097-8cde-494e-af83-938a7c6d4c5a.png)

## Acceptance Criteria

- [x] Encounter card avatars look normal
- [x] Other places where Avatar Group/ Avatar is used does not break

## Implementation details

n/a

## Testing notes

n/a

**Comment by noahjade** [comment]
lgtm!
