### ISSUE TITLE
Add Visual Map of Entries

### ISSUE THREAD

**Issue by UoA-sjer215** [se701team3/Forgettable#246]
## Description
 Add a Visual map that shows users where their encounters were. The map should be on the Encounters page. User encounters that were not stored using the Google Maps API data should not be shown.

Map would appear as a marker cluster like below:
![image](https://user-images.githubusercontent.com/68830694/160213795-63b72987-c3d6-461a-b44f-089faf3e7541.png)

Blocked by #325 

## Acceptance Criteria

- [ ] Visual map appears below the Encounters page

## Implementation details
Google has documentation on how to achieve a similar result [here](https://developers.google.com/maps/documentation/javascript/marker-clustering)

## Testing notes
New tests will need to be created to check if this new functionality works as intended.

**Comment by Dj5822** [comment]
Approved.
