### ISSUE TITLE
Add Company model and Integrate

### ISSUE THREAD

**Issue by UoA-sjer215** [se701team3/Forgettable#248]
## Description
 Add a company model where users are the ones that create and assign people to it to group people together based on company

## Acceptance Criteria

- [ ] create new database collection
- [ ] alter user and person model to include company
- [ ] create new endpoints for company and create new calls 

## Implementation details
you would first need to add a new collection in the mongoDB and then change the persons and users models to be able to store the information of what companies there are and what company a person belongs to. Maybe implement a new getPersons based on company.

## Testing notes
New tests will need to be created to check if this new functionality works as intended.

**Comment by jmor528** [comment]
Looks good to me
