### ISSUE TITLE
Add finishing touches to person profile page 

### ISSUE THREAD

**Issue by lin8231** [se701team3/Forgettable#254]
## Description
 
Person profile page is missing some QOL improvements as well as some minor missing functionalities. 
This includes:
* Better error handling
* Better success/error messages
* Modals for encounters and deletion confirmation 
* Routes are correct

## Acceptance Criteria

- [ ] Has better error handling
- [ ] Has better success/error messages
- [ ] Has modals for encoutners and deletion confirmation 
- [ ] Routes have been correctly implemented. 

## Implementation details

n/a

## Testing notes

n/a

**Comment by butterplup** [comment]
LGTM
