### ISSUE TITLE
Encounter Card click handling fixes

### ISSUE THREAD

**Issue by rainasong** [se701team3/Forgettable#263]
## Description
 
Currently only the center area of the EncounterCard is clickable. This is because when I created it I put onClick listener on the inner part of the Card component, not covering the entire component and it's implemented like that to avoid click propagation to the 'Delete' button. However, we found a one-line solution to fix click propagation now.

## Acceptance Criteria

- [ ] Add stop propagation to Delete button onClick handler
- [ ] Add stop propagation to Card onClick handler
- [ ] Make sure clicking on one component does not trigger the other component

## Implementation details

n/a

## Testing notes

n/a

**Comment by rushaan01** [comment]
Looks good to me
