### ISSUE TITLE
Clean up dateFormatter duplicate functions

### ISSUE THREAD

**Issue by lin8231** [se701team3/Forgettable#268]
## Description
 
There are two functions in the dateFormatter.js file that do very similar things, and they keep having conflicts with each other. 
Only one of them is needed. 

## Acceptance Criteria

- [ ] Only one of the duplicate functions is kept
- [ ] Update everywhere in the app that uses the removed function to use the new combined function 
- [ ] Update any other errorhandling logic 
- [ ] Add tests for date formatters

## Implementation details

n/a

## Testing notes

n/a

**Comment by rainasong** [comment]
TYSM for bringing this up!! Issue approved
