### ISSUE TITLE
Edit account details

### ISSUE THREAD

**Issue by cdra334** [se701team3/Forgettable#27]
## Description
 
Allow the user to edit their account details e.g. password, email, etc.

## Acceptance Criteria

- [ ] An option to edit account details
- [ ] Updated details should appear on the appropriate pages
- [ ] Content in database should also update to reflect these changes

## Implementation details

This will be set up after the initial project skeleton has been merged to the main.

## Testing notes

n/a

**Comment by lin8231** [comment]
Issue obsolete. Team decided on Firebase auth, we no longer handle any handling of user accounts.
