### ISSUE TITLE
Fix encounter card summary component 

### ISSUE THREAD

**Issue by lin8231** [se701team3/Forgettable#270]
## Description
 
Right now the EncounterSummary component crashes the app when hovered, and has styling issues.
![image](https://user-images.githubusercontent.com/62003343/159105881-355c68ab-86c5-4d02-8d7e-38ee7cb4dc69.png)

## Acceptance Criteria

- [x] Component doesn't crash app 
- [x] Fix component styling
- [x] Rename to EncounterCardSummary for consistency
- [x] Add tests if missing
- [x] Convert this to JS

## Implementation details

n/a

## Testing notes

n/a

**Comment by rainasong** [comment]
LGTM!
