### ISSUE TITLE
Update Create/Edit Person page

### ISSUE THREAD

**Issue by rainasong** [se701team3/Forgettable#271]
## Description
 
This page currently does not entirely match the desired styling and functionalities, need debugging and error fixing.
![Screen Shot 2022-03-19 at 5 08 56 PM](https://user-images.githubusercontent.com/37087904/159106078-18328c93-ee55-406f-90a7-96613b1df79a.png)

## Acceptance Criteria

- [x] Styling matches the style guide
- [x] Save functionality works, successfully update a person's information
- [x] Delete functionality works, successfully delete a person and return back
- [x] Create person functionality works, successfully creates a person and forward to create encounter page
- [x] Social media modal handles cases where the input social media platform does not exist
- [x] Change photo functionality works, successfully upload an image and replace the avatar preview image

## Implementation details

n/a

## Testing notes

Ensure all ACs are checked

**Comment by lin8231** [comment]
Great issue, thanks for raising this
