### ISSUE TITLE
Global stying fixing

### ISSUE THREAD

**Issue by rainasong** [se701team3/Forgettable#275]
## Description
 
Currently since different people wrote different files the styling for each page is not quite consistent and does not entirely match the style guide, so really need a global styling fix.

## Acceptance Criteria

- [x] Styling across the whole app matches the style guide
- [x] Styling methods are consistent for similar components
- [x] Styling sheets use global variables for font weight, font size etc.
- [x] Remove unnecessary styling code
- [x] Move all stylings to CSS modules if possible
- [x] Dark mode styling is consistent with the style guide

## Implementation details

n/a

## Testing notes

n/a

**Comment by noahjade** [comment]
o7 lgtm and goodluck

**Comment by rainasong** [comment]
> o7 lgtm and goodluck

hahaha yea good luck to me😂
