### ISSUE TITLE
Fix Firebase auth in frontend and add error/invalidation handling logic 

### ISSUE THREAD

**Issue by lin8231** [se701team3/Forgettable#276]
## Description
 
Currently you are required to log in every time you refresh the page, which is not a very ideal user experience. 
Auth logic needs a revamp to make sure that this doesn't happen, and add loading screens and error handling etc. 
Also, there is no logic to sign the user out automatically when a token has expired. This means that the user get stuck in a limbo signed-in-but-nothing-works state

## Acceptance Criteria

- [ ] Refreshing does not require user to sign in again 
- [ ] Session is maintained
- [ ] If token is invalidated, the user is signed out and redirected to sign in screen
- [ ] User can sign in properly
- [ ] User can have an account created when signing in if they don't have one already
- [ ] Other auth logic all work properly 
- [ ] Can sign out properly

**Comment by jimwang6012** [comment]
LGTM!
