### ISSUE TITLE
Reorganise routes to be cleaner 

### ISSUE THREAD

**Issue by lin8231** [se701team3/Forgettable#277]
## Description
 
Currently routes are all rendered in App.js, and the loggedIn/logginIn/notLoggedIn states are not handled very comprehensively. 
This should be moved out into a router component which handles all the conditional logic

## Acceptance Criteria

- [ ] Page router can route to all existing pages without breaking them
- [ ] Page router can handle different states and conditionally render routes
- [ ] Page router accounts for NavBar
- [ ] There is no more routing logic in App.js

**Comment by jimwang6012** [comment]
LGTM!
