### ISSUE TITLE
Signing up for frontend

### ISSUE THREAD

**Issue by jyao244** [se701team3/Forgettable#28]
## Description
 
Allow user to sign up a new account by filling in their personal informations, such as email, passward, user name etc. When signing up an account, user's informations should be verified before the account is successfully created. After signing up, user's informations should be stored in the database.
## Acceptance Criteria

- [x] User should be able to fill in their information and creat an account easily.
- [x] User's information should be verified before submitting.
- [x] User's information should be stored in the database.
## Implementation details

After the initial frontend setup and UI design is done, the signing up page can be created. After that, the functions of the page can be added to enable input verifying and data transmission.
## Testing notes

n/a

**Comment by noahjade** [comment]
PR #204 completes this logic. However, as we are using google auth through firebase the user does not have to enter so much information, and currently all we store about them is their name.
