### ISSUE TITLE
Auth loading state and auth flow touchup 

### ISSUE THREAD

**Issue by lin8231** [se701team3/Forgettable#281]
## Description
 
Auth flow works but the loading screen is very bare bones. Needs prettifying. 
Also general touch ups needed for auth flow

## Acceptance Criteria

- [ ] Loading screen is pretty
- [ ] Auth flow is touched up 
- [ ] Code is cleaned up
- [ ] All auth code is checked over for readability

## Implementation details

n/a

## Testing notes

n/a

**Comment by lusicle** [comment]
lgtm
