### ISSUE TITLE
Fix inconsistent/missing/incorrect prop types and props through the app 

### ISSUE THREAD

**Issue by lin8231** [se701team3/Forgettable#285]
## Description
 
There's currently a lot of prop type inconsistencies, namely:
Person drawer asks for an onEdit prop of boolean type, this is wrong
Person page missing first-met prop 
EncounterCardSummary asks for a dateMet as a string, this is wrong
EncounterCard's prop needs to be updated to encounterDetails 
Encounter drawer shuoldn't require last name

## Acceptance Criteria

- [x] Person drawer onEdit has correct prop type
- [x] Person page has firstMet prop
- [x] EncounteCardSummary has a dateMet Date prop
- [x] EncounterCard's prop updated to encounterDetails
- [x] Encounter drawer does not require last name

## Implementation details

n/a
## Testing notes

n/a

**Comment by lusicle** [comment]
lgtm
