### ISSUE TITLE
Fix `GET /persons/:id` endpoint

### ISSUE THREAD

**Issue by AdamAWiener** [se701team3/Forgettable#288]
## Description
 
A previous change slightly altered this endpoint and left it non-functional under certain conditions.
Sometimes the endpoint returns a 500 code or just times out entirely.

## Acceptance Criteria

- [ ] Restore endpoint to its previous functional state 

## Implementation details

Issue seems to be with `getPersonById()` in the person controller.

## Testing notes

All existing tests should pass!

**Comment by lin8231** [comment]
Issue approved!
