### ISSUE TITLE
Create Mongoose User Model

### ISSUE THREAD

**Issue by sdiv877** [se701team3/Forgettable#29]
## Description
 
Create a `User` model for use with mongoose, this will help to encapsulate retrieving data for a `User` from the database.

## Acceptance Criteria

- [x] Create a `user.model.ts` file in `Forgettable/backend/src/models`
- [x] Implement the schema detailed below

## Implementation details

The following schema should be followed for the model:
```json
{
    "_id": ,
    "first_name": ,
    "last_name": ,
    "user_name": ,
    "persons": ["ObjectID('pid')"]
}
```

**Comment by AdamAWiener** [comment]
We've altered this schema slightly to no longer include a `user_name` and to now include an `auth_id` for use with firebase.
