### ISSUE TITLE
Fix create person page

### ISSUE THREAD

**Issue by rainasong** [se701team3/Forgettable#295]
## Description
 
Due to changes in routings currently it's not correctly detecting if it's 'create' or 'edit' person. 

## Acceptance Criteria

- [x] Enter the correct page when create/edit buttons are clicked
- [x] POST and PUT APIs are called correctly
- [x] If it's create person page, goes to create encounter page after 'save' is clicked.

## Implementation details

n/a

## Testing notes

n/a

**Comment by noahjade** [comment]
uh oh. Issue LGTM tho!

**Comment by lusicle** [comment]
lgtm
