### ISSUE TITLE
Fix page routing redirection on refresh and add 404 page

### ISSUE THREAD

**Issue by lin8231** [se701team3/Forgettable#296]
## Description
 
Right now, when you refresh the page, you get forced to go back to the home page. We want to make it so that when you refresh, you can stay on the same page that you were on before. 

## Acceptance Criteria

- [ ] 404 page exists
- [ ] Route redirection is fixed, refreshing does not redirect
- [ ] Bad pages go to 404

## Implementation details

n/a

## Testing notes

n/a

**Comment by rainasong** [comment]
Issue LGTM!
