### ISSUE TITLE
Creating and setting up MongoDB

### ISSUE THREAD

**Issue by hajineats** [se701team3/Forgettable#3]
- [x] Registering MongoDB account through group gmail account
- [x] Creating MongoDB cluster 
- [x] Distributing URI & pw to the group

**Comment by AdamAWiener** [comment]
Mongo clould account setup using group email and password. 

The cluster and DB can be accessed with the following connection: ```mongodb+srv://se701team3:nENH`n8ham(\C{my@cluster0.yfnvo.mongodb.net/forgettableDB?retryWrites=true&w=majority```

**Comment by AdamAWiener** [comment]
Mongo clould account setup using group email and password.

The cluster and DB can be accessed with the connection posted in the backend discord channel.
