### ISSUE TITLE
Handle string overflow for small components

### ISSUE THREAD

**Issue by lin8231** [se701team3/Forgettable#302]
## Description
 
Some places in the app we have very limited space for text. We need to make sure that when there is text overflow, it looks normal

## Acceptance Criteria

- [ ] All text overflow is handled
- [ ] This includes PersonCards and EncounterCards
- [ ] Includes PersonCardSummary and EncounterCardSummary componetsn

## Implementation details

n/a

## Testing notes

n/a

**Comment by rainasong** [comment]
Issue lgtm!
