### ISSUE TITLE
Fix frontend bugs

### ISSUE THREAD

**Issue by rainasong** [se701team3/Forgettable#304]
## Description
 
Fix the following existing bugs on frontend.

## Acceptance Criteria

- [x] Fix encounter modal size, add min width and height to it and match with style guide
- [x] Fix search bar styling (both dark and light mode), search bar drop-down width, search input text styling
- [x] Fix search drop down list event handling logics and routings
- [x] Fix homepage encounter summary card click event handling logic
- [x] Fix homepage max width for summary cards on large screens
- [x] Fix homepage recent encounter wording (change from 'recently encounters' to 'recent encounters')
- [x] Fix encounter drawer and person drawer overflowing on small screens issue
- [x] Fix navbar item selection not match with page issue
- [x] Fix input component dark mode styling
- [x] Fix avatar image not showing/blinking
- [x] Fix create person posting image not successful issue
- [x] Fix global CSS to not use magic numbers

## Implementation details

n/a

## Testing notes

n/a

**Comment by lin8231** [comment]
Issue approved!
