### ISSUE TITLE
Convert remaining TS files into JS for frontend 

### ISSUE THREAD

**Issue by lin8231** [se701team3/Forgettable#306]
## Description
 
Team started with a TS repo but decided to shift to JS, need to clean up files that are TS 

## Acceptance Criteria

- [ ] All TS and TSX are converted and translated to JS
- [ ] remove TS dependencies 
- [ ] Make sure app still runs

## Implementation details

n/a

## Testing notes

n/a

**Comment by lusicle** [comment]
lgtm
