### ISSUE TITLE
Add loading screens to add/edit person and encounters

### ISSUE THREAD

**Issue by lin8231** [se701team3/Forgettable#312]
## Description
 
Right now, when we try to add/edit a person or add an encounter, there is no loading when the user clicks submit. 
It just stays there until the API call comes back and then we navigate. This means the user can click the submit button a bunch of times - no good.

## Acceptance Criteria

- [ ] After submitting add person, loading screen shows while it loads
- [ ] Same for edit person
- [ ] Same for add encounter
- [ ] All toasts still work correctly
- [ ] All navigation still work correctly

## Implementation details

n/a

## Testing notes

n/a

**Comment by lanxdrey19** [comment]
LGTM
