### ISSUE TITLE
Miscellaneous frontend bugs

### ISSUE THREAD

**Issue by hajineats** [se701team3/Forgettable#319]
## Description
 
Bunch of frontend bugs that need to be fixed.
- different components on different pages have different fields missing/incorrect (because unmarshalling inconsistency)
- social media not working
- date prop has an issue
- Bunch of tests not passing

## Acceptance Criteria

- [x] Unmarshall data a unified way so it's consistent for every page
- [x] Get social media link to show
- [x] Added unmarshaller for data
- [x] Fixed date prop type issue
- [x] Make sure all the tests pass
    - EncounterCard.test.js
    - PersonCard.test.js
    - NavBar.test.js
    - Index.test.js
    - EdiPerson.test.js

## Implementation details

n/a

## Testing notes

n/a

**Comment by jimwang6012** [comment]
LGTM!
