### ISSUE TITLE
Update `time_updated` with `PUT` endpoints

### ISSUE THREAD

**Issue by AdamAWiener** [se701team3/Forgettable#323]
## Description
 
When the `PUT /encounters` and ` PUT /persons` endpoints are called, we need to update the `time_updated` field of the modified item so that we can track recently changed items and display them in order on the front end.

## Acceptance Criteria

- [ ] `time_updated` updates to current time when `PUT /encounters/:id` or `PUT /persons/:id` are called successfully.

## Implementation details

This will be a change related to the respective endpoints' controller files.

## Testing notes

Please ensure all existing tests pass!

**Comment by hajineats** [comment]
Approved!

**Comment by jimwang6012** [comment]
LGTM!
