### ISSUE TITLE
Create new master branch

### ISSUE THREAD

**Issue by BraveNewWord** [se701team3/Forgettable#324]
## Description
We need to create a new master branch for assignment 2

## Acceptance Criteria

- [x] we have a new master branch

## Implementation details
Make a new branch called main-a2 and it will be the new master branch

## Testing notes
n/a

**Comment by hmit106** [comment]
Shouldn't the new main be called something like main-part-2 or main-team-02, so that it's clear why there is an existing main and a new main for the second part of the assignment?

**Comment by BraveNewWord** [comment]
> Shouldn't the new main be called something like main-part-2 or main-team-02, so that it's clear why there is an existing main and a new main for the second part of the assignment?

Ok it will be called main-a2

**Comment by BraveNewWord** [comment]
Ok we have a new master branch called main-a2
