### ISSUE TITLE
Add feature to display company info

### ISSUE THREAD

**Issue by jmor528** [se701team3/Forgettable#326]
## Description
New page to display company info and people associated with it

## Acceptance Criteria

- [x] new page to display company info and people associated with it

## Implementation details

Before backend is setup with company endpoints, use mock data for the company info according to company model. 

- User creates new entries for companies, they can specify all the fields except list of employees. 
- The user then can attempt to create a new person, and in the company field, they can choose one of the list of companies that they created entries for. The backend will then add that person to the company model in the db 
- When the user views the company entry, they should find the person they just created listed there and their names would link back to their profiles

**Comment by mdar365** [comment]
LGTM!
