### ISSUE TITLE
API Design

### ISSUE THREAD

**Issue by hajineats** [se701team3/Forgettable#4]
- [x] Based on frontend page requirements, figure out flexible REST API design
- [x] Think of GET, POST, DELETE, PUT
- [x] Defer authentication concern for now

**Comment by hajineats** [comment]
### From Frontend

> **MUST HAVES: (MVPest of MVPs)**
Account management/ Auth
Creating an account
Ability to sign in 
Adding new people (enter a person’s information)
Birthday field
Company field (db)
Social media link field(s)
Adding information about a new encounter with someone
Edit profile 
Viewing list of people that you have added
Viewing information/encounters of each  person that you have added
Delete people


> **Pages:**
SIgn in page
Sign up page 
Create person page 
Name
Birthday
Organisation
Social media link
Where you met
Date you met 
Their interests
(Initial) encounter details 
Edit profile UI (can be pop up, or new page?)
People list page
Show list of people (profile pic + description)
Button to create person 
Person details page 
Show profile info 
Show encounters
Delete person 
	
> **Each encounter has**
Date
Place 
Description

**Comment by butterplup** [comment]
Possibly use a frontend based Auth0 authentication which returns a JSON Web Token to be passed in the headers with any other API request.
