### ISSUE TITLE
Create search bar component

### ISSUE THREAD

**Issue by lin8231** [se701team3/Forgettable#47]
## Description
Create the search bar component with autocompletion. It will be reused across several pages. 

Initial mocks:
![image](https://user-images.githubusercontent.com/62003343/157045250-bcd1367b-f162-4ce3-b0e9-8e52cd91ae76.png)

## Acceptance Criteria

- [ ] Search bar has UI consistent with mocks
- [ ] Search bar has proper placeholder text 
- [ ] Search bar has autocompletion 
- [ ] Search bar sends search queries properly
- [ ] Search bar triggers correct results to be returned from backend
- [ ] Search bar is able to receive dynamic styles
- [ ] Search bar is responsive

## Implementation details

* Suggest just creating a component which wraps a library component + custom styling

## Testing notes

* Please add tests to ensure that each of the above A/Cs works as intended

**Comment by lin8231** [comment]
@butterplup please review ticket

**Comment by butterplup** [comment]
LGTM 👍

**Comment by noahjade** [comment]
Was completed with pr #176
