### ISSUE TITLE
Create settings page 

### ISSUE THREAD

**Issue by lin8231** [se701team3/Forgettable#48]
## Description
 
Create the settings page

## Acceptance Criteria

- [x] Settings page UI should be consistent with mocks
- [x] Settings page should be responsive 
- [x] All settings page endpoints should be hooked up (NOT including "log out" - this should be part of the auth issue <INSERT LINK>)
- [x] Settings page toggles dark/light mode 

## Implementation details

Log out should be done with an Auth issue, or if not, done by the person who did the auth issue. 

## Testing notes

Please add tests to ensure all of the above A/C works as intended

**Comment by lin8231** [comment]
@lanxdrey19 please review ticket

**Comment by lanxdrey19** [comment]
LGTM :) Sorry for late reply. I fell sick
