### ISSUE TITLE
Create/Edit Person Page

### ISSUE THREAD

**Issue by dkap937-209** [se701team3/Forgettable#50]
## Description
 
User is able to create a new person they have met and be able to edit their information after the person has been created.

## Acceptance Criteria

- [ ] Person can be created and be added to the list of other persons the user has met
- [ ] User is able to edit information about the person after the person has already been created
- [ ] Page Design is consistent with mocks

## Implementation details

Will make use of avatar(#51), input field, and button component.

## Testing notes

- [ ] When a new person is created it is added to the list of persons
- [ ] If a person's information is updated, the UI should reflect the changes made to the person's information

##Reviewer
@noahjade

**Comment by noahjade** [comment]
LGTM! Approving it now :)
