### ISSUE TITLE
Create Avatar Component

### ISSUE THREAD

**Issue by dkap937-209** [se701team3/Forgettable#51]
## Description
 
An avatar component that will be used to show an image of a person

## Acceptance Criteria

- [ ] Avatar can be changed to show an image that the user chooses
- [ ] If no image is provided a default image should be used

## Implementation details

Will be dependent on what component library is used.

## Testing notes

n/a

## Reviewer
@lusicle

**Comment by lin8231** [comment]
Closing this issue as this component is no longer needed as decided at team meeting last Tuesday.
