### ISSUE TITLE
Create PUT /persons/<personID> endpoint

### ISSUE THREAD

**Issue by schi314** [se701team3/Forgettable#56]
## Description
Create an endpoint for changing a person's data in the database

## Acceptance Criteria
- [x] Create a new function in `person.service.ts` called `updatePerson()` (or equivalent)
- [x] Create a new function in `person.controller.ts` called `updatePerson()` (or equivalent)
- [x] Attach the `updatePerson()` function to `/persons/:personID` in `person.route.ts`

## Implementation details

- [x] Request requires a `firebase_token` in headers
- [ ] Request requires a JSON body with `{ first_name: string, last_name: string, birthday: Date, interests: string[], organisation: string, time_added: Date, how_we_met: string}`
- [x] Success gives 204 No content
- [ ] Invalid request JSON body returns 400 Bad Request
- [x] Invalid token returns 401 Unauthorized

## Testing notes

* Test that the person's data has changed in the database

**Comment by hajineats** [comment]
SGTM!
