### ISSUE TITLE
Create Dashboard Page

### ISSUE THREAD

**Issue by lusicle** [se701team3/Forgettable#58]
## Description
Dashboard which acts as the Homepage, contains recent user and encounter lists
![Screen Shot 2022-03-11 at 6 48 06 PM](https://user-images.githubusercontent.com/37087904/157809894-ece805e1-f217-4fd4-bcb4-fb11f27bdbcb.png)
![Screen Shot 2022-03-11 at 6 48 22 PM](https://user-images.githubusercontent.com/37087904/157809926-8895eefb-719c-4147-929d-a588b1941612.png)

## Acceptance Criteria
- [x] Design matches HiFi mockups
- [x] Properly display recent users
- [x] Properly display recent encounters
- [x] Search functionality
- [x] New entry functionality

## Implementation details
Requires #57, #47, #51 

## Testing notes
n/a

**Comment by rainasong** [comment]
Search functionality on dashboard:
- Auto complete + pop up of search results, both person and encounter can be searched
Hover over behaviour on both person and encounter cards:
- Should show a preview of either person or encounter details

**Comment by noahjade** [comment]
LGTM! I might break some of the tasks down for easier PR tracking since this is a hefty one, but this issue is great :)
