### ISSUE TITLE
Set up firebase auth for frontend 

### ISSUE THREAD

**Issue by ckar364** [se701team3/Forgettable#61]
## Description
Create sign in page to allow users to access or create their account. Allow log out through log in page. 

## Acceptance Criteria
- [x] User can sign in through firebase successfully 
- [ ] User is provided with an appropriate message if auth is unsuccessful
- [ ] "Forgot Password?" and "Create Account" links work as intended.
- [ ] User is able to successfully create an account or retrieve password 
- [x] Sign In page UI is consistent with planned design.
- [x] Sign in page is responsive 
- [ ] User is able to log out from settings page

## Implementation details
Since the team decided to use firebase auth, this eliminates the need for most things to do with sign in and sign up - the UI required is minimal. As a result, 

## Testing notes
Ensure functionality works as intended and UI renders correctly. 
Make sure all firebase actions work correctly. 

## Reviewers
@lin8231

**Comment by lin8231** [comment]
Updated issue to conform with updated UI design, LGTM
