### ISSUE TITLE
Create Input component

### ISSUE THREAD

**Issue by ckar364** [se701team3/Forgettable#63]
## Description
Create Input component used throughout the UI. Various stylings may be applied. Input may be associated with a label.

## Acceptance Criteria
- [ ] Input component renders correctly based on UI design mocks.
- [ ] User data in the Input component passed correctly to its destination.
- [ ] Input component can be styled differently based on different styles that are applied.
- [ ] Input component can be associated with a label.

## Implementation details
Using Material UI library. Create a wrapper that allows the Input component to be customised to match UI design.

## Testing notes
Ensure that user data is passed correctly to its destination and the Input component renders correctly.

## Reviewers
@noahjade

**Comment by noahjade** [comment]
"Dependent on libraries used" can be updated now. We are using MUI (material ui) so for the implmentation for this it would be creating a wrapper that will customize the base material ui input component to match our designs.

Otherwise this ticket is great so I am going to approve it :)
