### ISSUE TITLE
Create 'Getting Started / How to Run' documentation

### ISSUE THREAD

**Issue by AdamAWiener** [se701team3/Forgettable#73]
## Description
 
We need documentation for how to set up and run the project locally. This should be neatly described by documentation in the readme.

## Acceptance Criteria

- [ ] describes steps to run the project locally
- [ ] describes what files/keys are required (e.g. mongoDB connection)

## Implementation details

na

## Testing notes

na

**Comment by cdra334** [comment]
LGTM
