### ISSUE TITLE
Update ESLint to be less strict for Frontend 

### ISSUE THREAD

**Issue by lin8231** [se701team3/Forgettable#86]
## Description
Currently the ESLint config that's been set up is very strict. Team would like to loosen the rules to ease developer pain.. Also to change config to JS

## Acceptance Criteria

- [ ] ESLint lints JS files
- [ ] ESLint rules less strict
- [ ] Optional: VS Code settings updated 

## Implementation details

n/a

## Testing notes

n/a

**Comment by lin8231** [comment]
@hajineats please review issue

**Comment by hajineats** [comment]
approved
