### ISSUE TITLE
Navigate from page to page using the NavBar

### ISSUE THREAD

**Issue by noahjade** [se701team3/Forgettable#91]
## Description
Once we have the NavBar component in place, we want to use it to allow the user to move between pages.

## Acceptance Criteria

- [ ] Clicking icons will take you to the appropriate pages
- [ ] When on a page, the relevant icon should be displayed as "selected"

## Implementation details

If page routing has not been set up yet, it will need to be set up as part of this task. Otherwise, it will be pretty simple.

## Testing notes

- Test appropriate selections are displayed.
- Test that it tries to redirect you to the right page (will need to mock functions)

**Comment by lin8231** [comment]
Ticket approved.
